---
log_level: DEBUG
rds_config:
  region: ap-southeast-2
  db_prefix: cf
  allow_user_provision_parameters: true
  allow_user_update_parameters: true
  allow_user_bind_parameters: true
  catalog:
    services:
    - id: ce71b484-d542-40f7-9dd4-5526e38c81ba
      name: rds-mysql
      description: RDS MySQL service
      bindable: true
      tags:
      - mysql
      - relational
      metadata:
        displayName: RDS MySQL
        longDescription: A RDS MySQL service
        providerDisplayName: Amazon Web Services
        documentationUrl: https://aws.amazon.com/documentation/rds/
        supportUrl: https://forums.aws.amazon.com/forum.jspa?forumID=60
      plan_updateable: true
      plans:
      - id: 5b8282cf-a669-4ffc-b426-c169a7bbfc71
        name: 5.6-micro-5G
        description: RDS MySQL 5.6 (db.t2.micro, 5G)
        metadata:
          costs:
          - amount:
              usd: 0.18
            unit: HOUR
          bullets:
          - Dedicated MySQL 5.6 server
          - MySQL 5.6
          - AWS RDS
          - 5G storage
        free: false
        rds_properties:
          shared: false
          db_instance_class: db.t2.micro
          engine: MySQL
          engine_version: 5.6.23
          allocated_storage: 5
          auto_minor_version_upgrade: true
          publicly_accessible: true
          copy_tags_to_snapshot: true
          db_security_groups:
          - default
      - id: 940b63c1-cc71-4bef-830f-231e4c4714db
        name: 5.6-micro-10G
        description: RDS MySQL 5.6 (db.t2.micro, 10G)
        metadata:
          costs:
          - amount:
              usd: 0.18
            unit: HOUR
          bullets:
          - Dedicated MySQL 5.6 server
          - MySQL 5.6
          - AWS RDS
          - 10G storage
        free: false
        rds_properties:
          shared: false
          db_instance_class: db.t2.micro
          engine: MySQL
          engine_version: 5.6.23
          allocated_storage: 10
          auto_minor_version_upgrade: true
          publicly_accessible: true
          copy_tags_to_snapshot: true
          db_security_groups:
          - default
    - id: a2c9adda-6511-462c-9934-b3fd8236e9f0
      name: rds-postgres
      description: RDS PostgreSQL service
      bindable: true
      tags:
      - postgres
      - relational
      metadata:
        displayName: RDS PostgreSQL
        longDescription: RDS PostgreSQL service
        providerDisplayName: Amazon Web Services
        documentationUrl: https://aws.amazon.com/documentation/rds/
        supportUrl: https://forums.aws.amazon.com/forum.jspa?forumID=60
      plan_updateable: true
      plans:
      - id: d03b544e-3be5-4aca-bb3b-11544247f313
        name: 9.4-medium
        description: RDS PostgreSQL 9.4 (db.t2.micro, 5Gb)
        metadata:
          costs:
          - amount:
              usd: 0.18
            unit: HOUR
          bullets:
          - Dedicated PostgreSQL 9.4 server
          - PostgreSQL 9.4
          - AWS RDS
          - 5G storage
        free: false
        rds_properties:
          shared: false
          db_instance_class: db.t2.micro
          engine: postgres
          engine_version: 9.4.4
          allocated_storage: 5
          auto_minor_version_upgrade: true
          publicly_accessible: true
          copy_tags_to_snapshot: true
          db_security_groups:
          - default
    - id: ea70df89-9ea3-4393-88d9-4e35c4ec43b8
      name: rds-shared
      description: RDS Shared Instances
      bindable: true
      tags:
      - relational
      - shared
      metadata:
        displayName: RDS Shared Instances
        longDescription: RDS services on a shared instance
        providerDisplayName: Amazon Web Services
        documentationUrl: https://aws.amazon.com/documentation/rds/
        supportUrl: https://forums.aws.amazon.com/forum.jspa?forumID=60
      plan_updateable: false
      plans:
      - id: 926ff9c8-6b1d-4648-ad5d-5b82a32811fb
        name: postgres-shared
        description: RDS PostgreSQL service on a shared instance
        metadata:
          bullets:
          - Shared PostgreSQL service
          - AWS RDS
        free: true
        rds_properties:
          shared: true
          engine: postgres
      - id: 42d56e29-d980-46bd-8e9d-61d572f5d224
        name: mysql-shared
        description: RDS MySQL service on a shared instance
        metadata:
          bullets:
          - Shared MySQL service
          - AWS RDS
        free: true
        rds_properties:
          shared: true
          engine: mysql
