---
jobs:
- name: rds-broker
  serial: true
  plan:
  - get: src
    trigger: true
  - task: run-tests
    file: src/ci/tests.yml
  - aggregate:
    - do:
      - task: prepare-manifest
        file: src/ci/prepare-manifest.yml
        input_mapping: {ci: src}
        output_mapping: {result: g-manifest}
        params:
          DOMAIN: system.g.cld.gov.au
      - put: g-cf
        params:
          manifest: g-manifest/manifest.yml
          path: build
          current_app_name: rds-broker

resources:
- name: src
  type: git
  source:
    uri: https://github.com/AusDTO/pe-rds-broker
    branch: master
- name: g-cf
  type: cf
  source:
    api: https://api.system.g.cld.gov.au
    username: ci-system-rds-broker
    password: ((g-password))
    organization: system
    space: rds-broker
