---
jobs:
- name: rds-broker-dg
  serial: true
  plan:
  - do:
    - get: src
      trigger: true
    - task: run-tests
      file: src/ci/tests.yml
    - aggregate:
      - do:
        - task: prepare-manifest
          file: src/ci/prepare-manifest.yml
          input_mapping: {ci: src}
          output_mapping: {result: d-manifest}
          params:
            DOMAIN: system.d.cld.gov.au
        - put: d-cf
          params:
            manifest: d-manifest/manifest.yml
            path: build
            current_app_name: rds-broker
      - do:
        - task: prepare-manifest
          file: src/ci/prepare-manifest.yml
          input_mapping: {ci: src}
          output_mapping: {result: g-manifest}
          params:
            DOMAIN: system.g.cld.gov.au
        - put: g-cf
          params:
            manifest: g-manifest/manifest.yml
            path: build
            current_app_name: rds-broker
    on_success:
      put: slack
      params:
        text: |
          :white_check_mark: $BUILD_JOB_NAME SUCCESS
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
    on_failure:
      put: slack
      params:
        text: |
          :x: $BUILD_JOB_NAME FAILED
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>

- name: rds-broker-y
  serial: true
  plan:
  - do:
    - get: src
      passed:
      - rds-broker-dg
    - task: run-tests
      file: src/ci/tests.yml
    - task: prepare-manifest
      file: src/ci/prepare-manifest.yml
      input_mapping: {ci: src}
      output_mapping: {result: y-manifest}
      params:
        DOMAIN: system.y.cld.gov.au
    - put: y-cf
      params:
        manifest: y-manifest/manifest.yml
        path: build
        current_app_name: rds-broker
    on_success:
      put: slack
      params:
        text: |
          :white_check_mark: $BUILD_JOB_NAME SUCCESS
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
    on_failure:
      put: slack
      params:
        text: |
          :x: $BUILD_JOB_NAME FAILED
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>

- name: rds-broker-b
  serial: true
  plan:
  - do:
    - get: src
      passed:
      - rds-broker-y
    - task: run-tests
      file: src/ci/tests.yml
    - task: prepare-manifest
      file: src/ci/prepare-manifest.yml
      input_mapping: {ci: src}
      output_mapping: {result: b-manifest}
      params:
        DOMAIN: system.b.cld.gov.au
    - put: b-cf
      params:
        manifest: b-manifest/manifest.yml
        path: build
        current_app_name: rds-broker
    on_success:
      put: slack
      params:
        text: |
          :white_check_mark: $BUILD_JOB_NAME SUCCESS
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
    on_failure:
      put: slack
      params:
        text: |
          :x: $BUILD_JOB_NAME FAILED
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>

resources:
- name: src
  type: git
  source:
    uri: https://github.com/AusDTO/pe-rds-broker
    branch: master
- name: b-cf
  type: cf
  source:
    api: https://api.system.b.cld.gov.au
    username: ci-system-rds-broker
    password: ((b-password))
    organization: system
    space: rds-broker
- name: d-cf
  type: cf
  source:
    api: https://api.system.d.cld.gov.au
    username: ci-system-rds-broker
    password: ((d-password))
    organization: system
    space: rds-broker
- name: g-cf
  type: cf
  source:
    api: https://api.system.g.cld.gov.au
    username: ci-system-rds-broker
    password: ((g-password))
    organization: system
    space: rds-broker
- name: y-cf
  type: cf
  source:
    api: https://api.system.y.cld.gov.au
    username: ci-system-rds-broker
    password: ((y-password))
    organization: system
    space: rds-broker
# z is a deliberate omission

- name: slack
  type: slack-notification
  source:
    url: ((slack-webhook-url))

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
